version: 2
updates:
  # Enable version updates for npm (React Native/Expo packages)
  - package-ecosystem: "npm"
    directory: "/Frontend"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "whispr-team"
    assignees:
      - "whispr-team"
    commit-message:
      prefix: "chore(frontend)"
      prefix-development: "chore(frontend)"
      include: "scope"
    # Group updates by dependency type
    groups:
      expo:
        patterns:
          - "expo*"
        update-types:
          - "minor"
          - "patch"
      react:
        patterns:
          - "react"
          - "react-native"
        update-types:
          - "minor"
          - "patch"
      babel:
        patterns:
          - "@babel/*"
          - "babel*"
        update-types:
          - "minor"
          - "patch"
    # Ignore specific dependencies that might cause breaking changes
    ignore:
      # Major version updates for React Native (often require manual migration)
      - dependency-name: "react-native"
        update-types: ["version-update:semver-major"]
      # Expo major versions can have breaking changes
      - dependency-name: "expo"
        update-types: ["version-update:semver-major"]
      - dependency-name: "expo-status-bar"
        update-types: ["version-update:semver-major"]
      # React major versions should be updated carefully
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      # Babel major versions can break builds
      - dependency-name: "@babel/core"
        update-types: ["version-update:semver-major"]
    
  # Enable version updates for Docker if you have Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "whispr-team"
    assignees:
      - "whispr-team"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions if you have workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first-thursday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "whispr-team"
    assignees:
      - "whispr-team"
    commit-message:
      prefix: "ci"
      include: "scope"
