version: '3.8'
services:
  expo-frontend:
    build: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npx expo start --lan
