sonar.projectKey=whispr-messenger_mobile-app
sonar.projectName=Whispr Messenger Mobile App
sonar.sources=src
sonar.tests=.
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=node_modules/**,web-build/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
